using assignments.oopclass;
System.Console.WriteLine("Enter information about your book ");
System.Console.Write("Name: ");
string namebook=Console.ReadLine();
Book constant=new Book(namebook);
System.Console.Write("Type: ");
constant.Booktype=Console.ReadLine();
System.Console.Write("Language: ");
constant.Language=Console.ReadLine();
System.Console.Write("Avtor: ");
constant.Avtor=Console.ReadLine();
System.Console.Write("Pages: ");
constant.Pages=Convert.ToInt32(Console.ReadLine());
System.Console.Write("Price: ");
constant.Price=Convert.ToInt32(Console.ReadLine());
constant.Bookinfo();
